version: "3.8"

services:
  db:
    image: mysql
    # command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=care
    networks:
      - mysql-network
    ports:
      - "3307:3306"
    volumes:
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data

  server:
    build:
      context: .
    container_name: meta-care-api
    entrypoint: ["/bin/bash", "./entrypoint.sh"]
    restart: always
    ports:
      - "6000:5005"
    links:
      - db
    depends_on:
      - db
    networks:
      - mysql-network

volumes:
  db-config:
  db-data:

networks:
  mysql-network:
    name: mysql-network
    driver: bridge
